### ISSUE TITLE
Training data requirement

### ISSUE THREAD

**Issue by ZhexuanZhou** [HUAWEI-Theory-Lab/deepqueuenet#1]
Hi, I find your paper is very interesting and I want to run the whole process myself. After going through your reporsitory, I cannont find the input data. Could you send me or tell me where to download the input data. Thanks for your time and wish you a happy chinese new year!

**Comment by CarlosGuemS** [comment]
According to the readme, the training data is hosted on dropbox since it's too big for GitHub: [https://www.dropbox.com/s/q56sx4hxe93n4g5/DeepQueueNet-dataset.zip?dl=0](https://www.dropbox.com/s/q56sx4hxe93n4g5/DeepQueueNet-dataset.zip?dl=0)
